### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by oldmanjk** [Josh-XT/AGiXT#1125]
### Description

![image](https://github.com/Josh-XT/AGiXT/assets/6403649/5bbfdd74-bf18-4c31-a903-69832860f5d4)
Documentation shows this. Never saw this.

### Steps to Reproduce the Bug

./AGiXT.ps1

### Expected Behavior

Documentation matches experience. Also, below you need an option for Python 3.12. Also, is latest stable considered latest?

### Operating System

- [ ] Linux
- [X] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [ ] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [ ] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Hello! Yes, I believe I need to update the screenshots in the documentation to reflect the PowerShell installer. The screenshot is of `AGiXT.sh` which is set up primarily to be used in Linux. I switched to a PowerShell installer for better cross platform use which has a slightly different selection.

For simplicity, I would recommend running option 1 for anyone who is not actively developing on the AGiXT platform.

![image](https://github.com/Josh-XT/AGiXT/assets/102809327/81163d4a-7a69-47b9-a4e4-ffe9f0a2453d)

**Comment by Josh-XT** [comment]
> If you already know the answer to that question is 3.10, why ask? 
- I thought the same thing about the Python version after reading the issue and updated the issue template: https://github.com/Josh-XT/AGiXT/commit/59f34445b7bedf4cbeedad14fab76e45bab2e033
- Text Generation Web UI direct support is being phased out. You can still use it installing it separately but trying to keep up with their changes in our installer proved to be a bit difficult, so I stopped doing it and I don't know the status of if it works anymore because I don't personally use it anymore.
- Text Generation Web UI and Stable Diffusion are in the process of being replaced by [ezlocalai](https://github.com/DevXT-LLC/ezlocalai)
- The `stable` release is the latest released version currently.

**Comment by Josh-XT** [comment]
Docs updated in #1128 - thank you for reporting the inconsistencies!
