### ISSUE TITLE
Let AI ask questions / Provide human feedback

### ISSUE THREAD

**Issue by ven-ven-ven** [Josh-XT/AGiXT#376]
### Problem Description

Currently, tasks and instructions do not offer means to get the AI to not veer off-course or attempt unnecessary steps. By allowing for human interjection in the form of feedback or answering questions, not only can we reformat the task list to suit our needs and address any possible hallucinations, but also reduce API calls, more streamlined goals and less data scraping, and account for user-specific cases.

### Proposed Solution

A proposed solution consists of:
1-Including a command to allow the AI to ask questions to the user.
2-Allowing the pausing of tasks/instructions to interject human feedback or guidance.
3-Including an additional textbox where to provide said information.
4-Ensuring the AI reworks the current step with the given feedback or answered questions.

### Additional Context

The implementation for this feature would be similar to that of Auto-GPT.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by greengeckowizard** [comment]
I think it's a good idea 💡 . In addition to that if you can also command it like to pause to add additional context on what you want?  For example if it started making an app and you wanted it to have a ui or settings like a certain way but you don't want to stop it and restart it as if already done a lot of work already to get to where it's at but you wanted to add additional context of what you wanted it to do like change this part of the app instead of this way. That's my take on adding to this idea hopefully y'all can build upon what in said about it.

**Comment by mongolu** [comment]
This would be nice to have.

**Comment by Josh-XT** [comment]
I don't disagree, just need to think of the best way to implement this.  The original intended purpose was for it to be autonomous with a single user input. I've expanded on that a lot with chains.  It was built to make the AI decide specifically when you give it an option to run commands. The best way to provide human feedback is by building a chain for what you want and specifying which commands should run when if you don't want the AI to decide.

I'm still pondering on the best way to approach this though. For now, setting up chains is the best answer until then.

**Comment by mongolu** [comment]
A good way to achieve this is by putting a 2-3 second wait until next execution.
If some input is made from the keyboard, then this 2-3 second wait ti e should increase maybe to 30 seconds. After this, if no Enter is detected, then ignore the user input.
If true, then should be included in the prompt to model.
I think it like this.

**Comment by Josh-XT** [comment]
> A good way to achieve this is by putting a 2-3 second wait until next execution. If some input is made from the keyboard, then this 2-3 second wait ti e should increase maybe to 30 seconds. After this, if no Enter is detected, then ignore the user input. If true, then should be included in the prompt to model. I think it like this.

The request goes from the front end to the back end, the back end does the work and returns the response to the front end for the user to see.  There is nowhere to put a wait because the request goes through to completion when it goes to the server, it would be a bit of a refactor to add any kind of break to this.

As I think of it, these are the issues:
- The issue is that it would turn 1 API endpoint for the instruction into 3 or more.
- The `run` function in `Interactions.py` would need reworked into multiple functions as well as anything that uses the `run` function and specifically has commands associated will need to be another function entirely.  I've avoided this with the `Instruct` prompt.

If you do not trust the agent to execute commands properly, I recommend not giving the agent commands to execute and using a chain to define which commands you want it to execute at what points.  Consider commands to be resources for your agent that you are providing as if they were an employee.  For example, as a Systems Engineer, I do not give a new employee full admin rights on day 1 to anything.  Once they're trained and certified to do be an admin in a specific system, they will get those rights.  Your agent is not trained to be an admin of anything, you have to give it a lot of context to "train" it for complex tasks or you're trusting the training data from whomever produced the model you're using.

All of that said, I've found GPT4 to be pretty reasonable about command execution with the single shot `Instruct` prompt and GPT3.5 and 4 to be very good at it with Smart Instruct.  I haven't found any smaller models useful for choosing what commands to execute, mostly because we don't have enough room to inject context in a 2K max token model.  The 4K of GPT3.5 and 8K+ of GPT4 are sufficient for a lot of things, but you still have to keep in mind that even they will need more context on "using" a lot of third party software.

**Comment by Josh-XT** [comment]
Another thought... We could have an option for agents command executions to create a chain of the commands it would have executed rather than executing them, then allowing you to execute the chain by choice after reviewing it. I think this would solve the need for user input between command runs right?

**Comment by Josh-XT** [comment]
Does #700 satisfy this well enough?
