### ISSUE TITLE
AGiXT to see Screens

### ISSUE THREAD

**Issue by birdup000** [Josh-XT/AGiXT#649]
### Feature/Improvement Description

Ever want an AI to solve problems for you LIKE view screens and fix stuff for you with that well now we can make that a reality!

### Proposed Solution

and it would be just like it processing an image...
then it outputs coordinates, and you have a "helper script" that takes a coordinate + left, right, middle etc... and does it
or you can go the traditional route, and actually incorporate some api based screen recorder that will dump to the ai... and again a helper script.

I AM RIPPING THIS FROM DISCORD AS THE IDEA IS SO GOOD THANKS @UltOnlineGamer in the discord server for that since he gets full credit towards this. 

### Acknowledgements

- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for everyone to understand why this feature request is needed in AGiXT.

**Comment by dominicOT** [comment]
@greengeckowizard 

😶🤔

Screen Analysis and Automation is what you mean, if I am right.

Quite tasky, it'd require implementing Convolutional Neuural Networks to train the model... pattern recognition as well.

Cool.

**Comment by Josh-XT** [comment]
I'm not 100% sure which approach will be taken yet. Currently we're scraping pages and interacting with them with Playwright and BeautifulSoup. I think some image classification for the images on pages to help identify those better and help browsing agent do it better.

**Comment by greengeckowizard** [comment]
> I'm not 100% sure which approach will be taken yet. Currently we're scraping pages and interacting with them with Playwright and BeautifulSoup. I think some image classification for the images on pages to help identify those better and help browsing agent do it better.

Check this out @Josh-XT 
https://pypi.org/project/pytesseract/

**Comment by Josh-XT** [comment]
I'm more looking for something that can **describe** images in good detail in text so that I can ask the AI if the image image is relevant to the task, then commit to memory if so during research phases.  So that it basically "saw" the image.  

I've been considering this approach kind of like describing something to a blind person who hasn't always been blind.  Explaining to the AI what is in the image may provide additional context in web searches that they would have otherwise not had.  We can easily discard descriptions of images that aren't relevant (ads, clipart, logos, etc) by asking the AI if the image described is relevant.

**Comment by dominicOT** [comment]
So we don't want this thing to just process the image - view and describe, it should also be able to classify to the images as 'relevant' or 'irrelevant' in relation to whatever description the user gives?


So can we say:

>> gathering a dataset of images,
>> having an image description and text description model trained to be able to extract meaning properties from the image(s) and provide descriptions based on those properties extracted and 
>> having a binary classifier trained to also determine the relevance of the image to a task

is sort of a way out...

> I'm more looking for something that can **describe** images in good detail in text so that I can ask the AI if the image is relevant to the task, then commit to memory if so during research phases. So that it basically "saw" the image.
> 
> I've been considering this approach kind of like describing something to a blind person who hasn't always been blind. Explaining to the AI what is in the image may provide additional context in web searches that they would have otherwise not had. We can easily discard descriptions of images that aren't relevant (ads, clipart, logos, etc) by asking the AI if the image described is relevant.

**Comment by dominicOT** [comment]
Let's say I want to make a documentation and I need images to give visual description of what I'm doing...

Imagine **a model** like Convo Neural Net, maybe ResNet or VGG that **can extract** meaningful properties from the images, **another model** like a Recurrent Neural Net (or maybe Transformer) that generates textual description based on those properties that was extracted and the **a binary classifier** that then determines the relevance of the image to your task and accompany it with some kind of decription (or writeup)...

Integrating these three models together will give just the result wanted, I think 🤔

What do you think..? @greengeckowizard @Josh-XT

**Comment by rlederer-C136** [comment]
> 

Have you tried using Oobabooga TGWebUI in multimodal mode? i have it setup with the 13b Vicuna model and a 13b parameter minigpt4 pipeline model and it is incredibly good at describing images you present to it. It turns out most llama based models can be pipelined to 'see' by connecting a multimodal model into a pipe. 

https://github.com/oobabooga/text-generation-webui/tree/main/extensions/multimodal

**Comment by Josh-XT** [comment]
> > 
> 
> Have you tried using Oobabooga TGWebUI in multimodal mode? i have it setup with the 13b Vicuna model and a 13b parameter minigpt4 pipeline model and it is incredibly good at describing images you present to it. It turns out most llama based models can be pipelined to 'see' by connecting a multimodal model into a pipe.
> 
> https://github.com/oobabooga/text-generation-webui/tree/main/extensions/multimodal

I'll try that out in the near future.  I wonder if llamacpp does this well also...

**Comment by Josh-XT** [comment]
We an run multimodal models now with [Local-LLM](https://github.com/Josh-XT/Local-LLM) such as ones with vision like Bakllava.  Some useful chains that could come of this:

- Take a screenshot and describe it
- Describe image at a path
- Describe pasted image
- Read text from an image
- Tell a story about an image

Plenty more useful chains can come from this. If anyone is inspired to make any, feel free to do a pull request with them.

**Comment by Josh-XT** [comment]
We have VLMs available in ezLocalai that can either comprehend and explain what is on the screen or can be fine tuned to do this on specific websites. I think this is going to show up as a natural ability of vision models in time and that there won't be any work to do here since ezlocalai already supports vision models.
